### PR TITLE
Add initial doxygen config...

### PR DESCRIPTION
**Pull request by foolswood**
it punts out not unusable docs.

More work would be required to make them good.

Also if we wanted another auto integration thingy: https://codedocs.xyz/

### CODE REVIEW

**Comment by foolswood** [comment]
Yeah, `doxygen -g` generates a default config, which I've tweaked a bit.
It's not too bad in an editor where you can search around it, but I can quite imagine it being horrendous on github.

**Comment by foolswood** [comment]
Do we still want the python implementation at all?

**Comment by ch3pjw** [comment]
We can ditch it for now :-)

**Comment by foolswood** [comment]
https://github.com/concert/libadiff/issues/56 for that.

**Pull request merged**
